name: website
on:
  push:
    branches:
      - master

jobs:   
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: rocker/verse:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate website
        run: Rscript render_site.R
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
